version: '3.8'

services:
  report-generator:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/app/workspace
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REPORT_DIR=/app/workspace
      - CMD_ALTERNATIVE=true
      - API_USERNAME=${API_USERNAME:-admin}
      - API_PASSWORD=${API_PASSWORD:-secure_password}
    restart: unless-stopped
    command: python run_api_server_8080.py
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/", "-o", "/dev/null" ]
      interval: 30s
      timeout: 10s
      retries: 3
