version: '3.8'

services:
  report-generator:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./workspace:/app/workspace
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/docs" ]
      interval: 30s
      timeout: 10s
      retries: 3
