version: '3.8'

services:
  report-generator:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./workspace:/app/workspace
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REPORT_DIR=/app/workspace
      - CMD_ALTERNATIVE=true
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/docs" ]
      interval: 30s
      timeout: 10s
      retries: 3
